unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind h previous-window
bind l next-window

bind v copy-mode

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind C-z
bind-key -T root C-a switch-client -T prefix-lua
set-option -g status-position bottom

set -g mode-keys vi


bind-key -T prefix-lua C-t run-shell "~/.config/zsh/lua_scripts/translate.lua >/dev/null 2>&1 &"
bind-key -T prefix-lua c run-shell "~/.config/zsh/lua_scripts/popup_util.lua bat"
bind-key -T prefix-lua n run-shell "~/.config/zsh/lua_scripts/popup_util.lua nvim"
bind-key -T prefix-lua N run-shell "~/.config/zsh/lua_scripts/popup_util.lua nvim_home"
bind-key -T prefix-lua t run-shell "~/.config/zsh/lua_scripts/popup_util.lua mvn_test"
bind-key -T prefix-lua l run-shell "~/.config/zsh/lua_scripts/popup_util.lua lazy_git"
bind-key -T prefix-lua H run-shell "~/.config/zsh/lua_scripts/popup_util.lua htop"
bind-key -T prefix-lua d run-shell "~/.config/zsh/lua_scripts/popup_util.lua lazy_docker"
bind-key -T prefix-lua m run-shell "~/.config/zsh/lua_scripts/popup_util.lua tldr"
bind-key -T prefix-lua g run-shell "~/.config/zsh/lua_scripts/gemini_float.lua"
bind-key -T prefix-lua a run-shell "~/.config/zsh/lua_scripts/auto_anotation.lua >/dev/null 2>&1 &"
bind-key -T prefix-lua h run-shell "~/.config/zsh/lua_scripts/popup_util.lua zsh_history"
bind r source-file ~/.tmux.conf \; display "Config recarregada!"

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor "twilight_dark"


run '~/.tmux/plugins/tpm/tpm'
